server:
  port: 9100
  servlet:
    context-path: /api
spring:
  security:
    oauth:
      check-token-uri: ${OAUTH_SERVER_ADDRESS:http://localhost:9010}/oauth/check_token
      client-id: bookstore
      client-secret: bookstore

  application:
    name: books-api
  liquibase:
    default-schema: book_store
    enabled: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_ADDRESS:localhost:5435}/books
    username: testuser
    password: postgres

  #    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    defer-datasource-initialization: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.PostgreSQL81Dialect
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
#  h2:
#    console:
#      enabled: true
logging:
  level:
    org:
      springframework: TRACE
    com:
      amazingbooks: TRACE
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:9500}/eureka